# CS161 Python Review Session

**Steven Chen**

### Why Use Python?

* Easy to learn
* Fast to write
* Easy to read (looks like pseudocode)!
* General purpose
* Plenty of useful libraries
* The de facto language of AI and machine learning


--------------------------------

### Installing and Using Python

Python is installed already on the Stanford AFS machines. To access them, SSH into rice.stanford.edu (that's where the project starter files are).

`ssh SUNETID@rice.stanford.edu`

To install on your own computer:

**Mac:** Python is already installed. To install the Numpy library, which is also used for the project:

`sudo easy_install pip`

`pip install numpy`

**Windows:** Download and install Anaconda, which gives you a Python install, a bunch of useful libraries, and a couple GUI programs:

`https://www.anaconda.com/download/`

**Ubuntu:** Python is already installed. To install Numpy:

`sudo apt-get install python-pip`

`pip install numpy`

---------------------------

### Python Language

Python is:

* **Dynamic:** Types (such as int, str, float) are not declared, but are inferred.

* **Interpreted:** Each line of code is read, interpreted, and run by Python, instead of compiling your entire program and then running the whole thing. This means you have an interpreter, where you can run one line of code at a time!

### Integers and Floats

In [1]:
# comments begin with a hash.

a = 6  # variables are declared without a type.
b = 3  # no semicolons needed

print b
print a + b
print max(a, b)  # python has useful built-in functions, such as min, max, sum

3
9
6


In [2]:
a = a + 1
a += 1

# Python doesn't have the ++ operator, like a++.

# the usual math operators:
c = a + b
d = a - b
e = a / b 
f = a * b
g = a ** b # a to the power of b

print g

512


In [3]:
pi = 3.1415  # declaring floats
e = 2.71828

print pi + e

5.85978


In [4]:
# Python numbers never overflow!
print g
print f

print g ** f

512
24
105312291668557186697918027683670432318895095400549111254310977536


### Strings

In [5]:
s = 'hello world' # declaring a string
s = "hello world" # single or double quotes, either works

string_length = len(s)  # len() gives the length of the string

print string_length

11


In [6]:
print s[1]  # indexing into a string gives a length 1 string.

# Python is zero-indexed! (First element is at position 0.)

e


In [7]:
# appending strings together is easy!
another = ' from python'
combined = s + another
print combined

hello world from python


In [8]:
# to append different types, you'll need to cast a type.

with_a_number = s + ' ' +  str(pi)

print with_a_number

hello world 3.1415


### Control Statements and Logic

In [9]:
speed = 90
cop_nice = True  # booleans are True or False


if speed < 60:
    get_ticket = False   # indenting represents what's inside a code block
    fine = 0
elif speed >= 60 and speed < 70:  # and, or are keywords written out in English
    if cop_nice:
        get_ticket = False
        fine = 0
    else:
        get_ticket = True
        fine = 100
elif speed >= 70:
    get_ticket = True
    fine = 200

    
print get_ticket, fine  # multiple things printed on the same line

True 200


**Note:** Indentation is very important in Python: it's how it knows what's inside or outside a block of code! Use 4 spaces or tabs, but don't mix them.

In [28]:
print "test 1:"

for i in range(10):  # for loops loop over a list or range.
    print i

print "test 2:"
    
for i in range(-2, 3):
    print i, i ** 2  # you can print multiple variables on one line
    
print "test 3:"
    
for i in range(5, 15, 2): # print from 5 to 15 (excluding 15), and step by 2 each time
    print i

test 1:
0
1
2
3
4
5
6
7
8
9
test 2:
-2 4
-1 1
0 0
1 1
2 4
test 3:
5
7
9
11
13


### Python Lists (Note: We use Numpy arrays in the project, which are faster.)

In [11]:
my_list = []  # making a new list. A list can contain any objects.

my_list.append(5)  # appending elements
my_list.append(6)
my_list.append(7)

print my_list

print my_list[1]

print sum(my_list)

[5, 6, 7]
6
18


In [12]:
for elem in my_list:  # iterating through the elements of a list
    print elem

5
6
7


In [13]:
for i, elem in enumerate(my_list): # enumerate, getting both index and element
    print('entry:')
    print(i)
    print(elem)

entry:
0
5
entry:
1
6
entry:
2
7


In [14]:
# list comprehensions are of the following form. One-line way to make a list!

big_list = [i for i in range(20)]
print big_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [29]:
# create a list consisting of squares of odd numbers from 0 to 29.

odd_squares = [i ** 2 for i in range(30) if i % 2 == 1]
print odd_squares

# the single line above is equivalent to the following:
alternate = []
for i in range(30):
    if i % 2 == 1:
        alternate.append(i ** 2)

print(alternate)

[1, 9, 25, 49, 81, 121, 169, 225, 289, 361, 441, 529, 625, 729, 841]
[1, 9, 25, 49, 81, 121, 169, 225, 289, 361, 441, 529, 625, 729, 841]


In [16]:
all_zeros = [0 for i in range(20)]
print all_zeros

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [31]:
# you can make a two-dimensional array by nesting a list comprehension inside another.
two_dimensional = [[i + j for i in range(5)] for j in range(3)]

print two_dimensional

print two_dimensional[1][2] # access the middle element (index 2) of the second list (index 1)

[[0, 1, 2, 3, 4], [1, 2, 3, 4, 5], [2, 3, 4, 5, 6]]
3


In [18]:
# list slices are an easy way to get a chunk of a list.

print big_list

chunk = big_list[3:14] # grab elements from index 3 to index 14 (not including index 14).

print chunk

last = big_list[-1] # grab the last element

print last

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
19


### Functions

In [19]:
# functions are defined as follows:

def fib(n):
    if n < 2:
        return 1
    else:
        return fib(n - 1) + fib(n - 2)

# the function ends when the indented block ends

# calling a function:
print fib(4)

5


In [20]:
# functions can take multiple parameters of any type

def multiply_each(number_list, x):
    output_list = []
    for number in number_list:
        output_list.append(number * x)
    return output_list

input_list = [1, 2, 3]
x = 5
output_list = multiply_each(input_list, x)

print output_list

[5, 10, 15]


### Numpy

Numpy is a popular Python numerical library that adds fast arrays and a bunch of useful math operations. We'll just be using the Numpy array:

In [21]:
# import the numpy library, and name it np for short

import numpy as np

In [22]:
# create a new numpy integer array of all zeros
A = np.zeros(6, dtype=int)

print A

[0 0 0 0 0 0]


In [23]:
# numpy arrays are fixed size: no appending or removing.

# they support interesting operations that run on each element:

A = A + 3

print A

B = np.random.rand(4) # array of 4 random numbers

print B

B = np.cos(B) # take the cosine of each number

print B

[3 3 3 3 3 3]
[0.30579772 0.12980659 0.2083816  0.81585157]
[0.9536071  0.99158695 0.97836701 0.68524843]


In [24]:
# multi-dimensional numpy arrays are easy to use:

matrix = np.zeros((3, 5), dtype=int)
# note the parentheses around the dimensions.

# 3 rows and 5 columns
print matrix

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [25]:
# working with 2d arrays:

dimensions = matrix.shape
print dimensions
print dimensions[0]
print dimensions[1]

# writing a value to the matrix:
matrix[2][1] = 5

print matrix
print matrix[2][1]

(3, 5)
3
5
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 5 0 0 0]]
5


In [26]:
# stepping through a 2d array:

rand_matrix = np.random.randint(0, 10, size=(3, 4))

print rand_matrix

for i in range(rand_matrix.shape[0]):
    for j in range(rand_matrix.shape[1]):
        print rand_matrix[i][j]

[[6 0 3 1]
 [4 6 0 0]
 [2 7 7 4]]
6
0
3
1
4
6
0
0
2
7
7
4


-------------------------------

### OK, let's go look at the programming project now!